$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path).Replace(".Tests.", ".")
. "$here\$sut"

function Create-DownloadFolder {
    $files = @"
#TYPE Selected.System.IO.DirectoryInfo
"FullName","Mode"
"TestDrive:\Bamse.Och.Tjuvstaden.2014.Swedish.480p.Dvd.Ac3-YstaJeppa","da---"
"TestDrive:\The.Walking.Dead.S05E15.PROPER.HDTV.x264-BATV[ettv]","da---"
"TestDrive:\The.Blacklist.S02E12.HDTV.x264-LOL[ettv]","da---"
"TestDrive:\The.Blacklist.S02E14.HDTV.x264-LOL[ettv]","da---"
"TestDrive:\The.Blacklist.S02E15.HDTV.x264-LOL[ettv]","da---"
"TestDrive:\Divergent (2014)","da---"
"TestDrive:\The.Blacklist.S02E16.HDTV.x264-LOL[ettv]","da---"
"TestDrive:\Fortitude.S01E01.INTERNAL.HDTV.x264-KILLERS[ettv]","da---"
"TestDrive:\Fortitude.S01E02.WEB-DL.XviD.MP3-RARBG","da---"
"TestDrive:\Fortitude.S01e02.Episode.Two.AlgernonWood-BlackBit","da---"
"TestDrive:\Fortitude S01E03 WEB-DL XviD-FUM[ettv]","da---"
"TestDrive:\Fortitude S01E04 WEB-DL XviD-FUM[ettv]","da---"
"TestDrive:\Fortitude S01E06 WEB-DL XviD-FUM[ettv]","da---"
"TestDrive:\Fortitude S01E07 WEB-DL XviD-FUM[ettv]","da---"
"TestDrive:\Fortitude S01E08 WEB-DL XviD-FUM[ettv]","da---"
"TestDrive:\Fortitude S01E09 WEB-DL XviD-FUM[ettv]","da---"
"TestDrive:\Fortitude S01E10 WEB-DL XviD-FUM[ettv]","da---"
"TestDrive:\The.Walking.Dead.S05E16.PROPER.HDTV.x264-KILLERS[ettv]","da---"
"TestDrive:\Jordskott - S01E08 - 1280x720 - H.264 - SweSub.mp4","da---"
"TestDrive:\Game of Thrones S05E01 WEBRip XviD-FUM[ettv]","da---"
"TestDrive:\Game of Thrones S05E02 WEBRip XviD-FUM[ettv]","da---"
"TestDrive:\Game of Thrones S05E03 WEBRip XviD-FUM[ettv]","da---"
"TestDrive:\Game of Thrones S05E04 WEBRip XviD-FUM[ettv]","da---"
"TestDrive:\The Maze Runner (2014)","da---"
"TestDrive:\Guitar.Hero.III.PC.The.Ultimate.Collection","da---"
"TestDrive:\The.Blacklist.S02E13.HDTV.x264-LOL.mp4","-a---"
"TestDrive:\The.Blacklist.S02E13.HDTV.x264-LOL.srt","-a---"
"TestDrive:\Game.of.Thrones.S05E01.WEBRip.XviD-FUM.avi","-a---"
"TestDrive:\Game.of.Thrones.S05E01.WEBRip.XviD-FUM.srt","-a---"
"TestDrive:\Game.of.Thrones.S05E01.HDTV.x264-Xclusive.mp4","-a---"
"TestDrive:\Game.of.Thrones.S05E02.HDTV.x264-Xclusive.mp4","-a---"
"TestDrive:\Game.of.Thrones.S05E03.HDTV.x264-Xclusive4iPT.mp4","-a---"
"TestDrive:\Game.of.Thrones.S05E04.HDTV.x264-Xclusive4iPT.mp4","-a---"
"TestDrive:\Game.of.Thrones.S05E01.HDTV.x264-Xclusive.srt","-a---"
"TestDrive:\Game.of.Thrones.S05E02.HDTV.x264-Xclusive.srt","-a---"
"TestDrive:\Wildest.Islands.Series.2.3of5.Vancouver.Island.Rivers.Of.Life.540p.PDTV.x264.AAC.MVGroup.org.mp4","-a---"
"TestDrive:\Bamse.Och.Tjuvstaden.2014.Swedish.480p.Dvd.Ac3-YstaJeppa\Bamse.Och.Tjuvstaden.2014.Swedish.480p.Dvd.Ac3-YstaJeppa.avi","-a---"
"TestDrive:\Bamse.Och.Tjuvstaden.2014.Swedish.480p.Dvd.Ac3-YstaJeppa\Bamse.Och.Tjuvstaden.2014.Swedish.480p.Dvd.Ac3-YstaJeppa.sub","-a---"
"TestDrive:\Bamse.Och.Tjuvstaden.2014.Swedish.480p.Dvd.Ac3-YstaJeppa\Bamse.Och.Tjuvstaden.2014.Swedish.480p.Dvd.Ac3-YstaJeppa.tbn","-a---"
"TestDrive:\Bamse.Och.Tjuvstaden.2014.Swedish.480p.Dvd.Ac3-YstaJeppa\Bamse.Och.Tjuvstaden.2014.Swedish.480p.Dvd.Ac3-YstaJeppa.idx","-a---"
"TestDrive:\The.Walking.Dead.S05E15.PROPER.HDTV.x264-BATV[ettv]\Sample","da---"
"TestDrive:\The.Walking.Dead.S05E15.PROPER.HDTV.x264-BATV[ettv]\The.Walking.Dead.S05E15.PROPER.HDTV.x264-BATV.mp4","-a---"
"TestDrive:\The.Walking.Dead.S05E15.PROPER.HDTV.x264-BATV[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\The.Walking.Dead.S05E15.PROPER.HDTV.x264-BATV[ettv]\the.walking.dead.s05e15.proper.hdtv.x264-batv.nfo","-a---"
"TestDrive:\The.Walking.Dead.S05E15.PROPER.HDTV.x264-BATV[ettv]\The.Walking.Dead.S05E15.PROPER.HDTV.x264-BATV.srt","-a---"
"TestDrive:\The.Walking.Dead.S05E15.PROPER.HDTV.x264-BATV[ettv]\Sample\sample-the.walking.dead.s05e15.proper.hdtv.x264-batv.mp4","-a---"
"TestDrive:\The.Blacklist.S02E12.HDTV.x264-LOL[ettv]\Sample","da---"
"TestDrive:\The.Blacklist.S02E12.HDTV.x264-LOL[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\The.Blacklist.S02E12.HDTV.x264-LOL[ettv]\the.blacklist.212.hdtv-lol.nfo","-a---"
"TestDrive:\The.Blacklist.S02E12.HDTV.x264-LOL[ettv]\The.Blacklist.S02E12.HDTV.x264-LOL.srt","-a---"
"TestDrive:\The.Blacklist.S02E12.HDTV.x264-LOL[ettv]\The.Blacklist.S02E12.HDTV.x264-LOL.mp4","-a---"
"TestDrive:\The.Blacklist.S02E12.HDTV.x264-LOL[ettv]\Sample\the.blacklist.212.hdtv-lol.sample.mp4","-a---"
"TestDrive:\The.Blacklist.S02E14.HDTV.x264-LOL[ettv]\Sample","da---"
"TestDrive:\The.Blacklist.S02E14.HDTV.x264-LOL[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\The.Blacklist.S02E14.HDTV.x264-LOL[ettv]\the.blacklist.214.hdtv-lol.mp4","-a---"
"TestDrive:\The.Blacklist.S02E14.HDTV.x264-LOL[ettv]\the.blacklist.214.hdtv-lol.nfo","-a---"
"TestDrive:\The.Blacklist.S02E14.HDTV.x264-LOL[ettv]\Sample\the.blacklist.214.hdtv-lol.sample.mp4","-a---"
"TestDrive:\The.Blacklist.S02E15.HDTV.x264-LOL[ettv]\Sample","da---"
"TestDrive:\The.Blacklist.S02E15.HDTV.x264-LOL[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\The.Blacklist.S02E15.HDTV.x264-LOL[ettv]\the.blacklist.215.hdtv-lol.mp4","-a---"
"TestDrive:\The.Blacklist.S02E15.HDTV.x264-LOL[ettv]\the.blacklist.215.hdtv-lol.nfo","-a---"
"TestDrive:\The.Blacklist.S02E15.HDTV.x264-LOL[ettv]\Sample\the.blacklist.215.hdtv-lol.sample.mp4","-a---"
"TestDrive:\Divergent (2014)\Divergent.2014.720p.BluRay.x264.YIFY.mp4","-a---"
"TestDrive:\Divergent (2014)\Divergent.2014.720p.BluRay.x264.YIFY.srt","-a---"
"TestDrive:\The.Blacklist.S02E16.HDTV.x264-LOL[ettv]\Sample","da---"
"TestDrive:\The.Blacklist.S02E16.HDTV.x264-LOL[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\The.Blacklist.S02E16.HDTV.x264-LOL[ettv]\the.blacklist.216.hdtv-lol.mp4","-a---"
"TestDrive:\The.Blacklist.S02E16.HDTV.x264-LOL[ettv]\the.blacklist.216.hdtv-lol.nfo","-a---"
"TestDrive:\The.Blacklist.S02E16.HDTV.x264-LOL[ettv]\Sample\the.blacklist.216.hdtv-lol.sample.mp4","-a---"
"TestDrive:\Fortitude.S01E01.INTERNAL.HDTV.x264-KILLERS[ettv]\Fortitude.S01E01.INTERNAL.HDTV.x264-KILLERS.mp4","-a---"
"TestDrive:\Fortitude.S01E01.INTERNAL.HDTV.x264-KILLERS[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\Fortitude.S01E01.INTERNAL.HDTV.x264-KILLERS[ettv]\fortitude.s01e01.internal.hdtv.x264-killers.nfo","-a---"
"TestDrive:\Fortitude.S01E01.INTERNAL.HDTV.x264-KILLERS[ettv]\Fortitude.S01E01.INTERNAL.HDTV.x264-KILLERS.srt","-a---"
"TestDrive:\Fortitude.S01E02.WEB-DL.XviD.MP3-RARBG\Fortitude.S01E02.WEB-DL.XviD.MP3-RARBG.avi","-a---"
"TestDrive:\Fortitude.S01E02.WEB-DL.XviD.MP3-RARBG\Fortitude.S01E02.WEB-DL.XviD.MP3-RARBG.nfo","-a---"
"TestDrive:\Fortitude.S01E02.WEB-DL.XviD.MP3-RARBG\Fortitude.S01E02.WEB-DL.XviD.MP3-RARBG.srt","-a---"
"TestDrive:\Fortitude.S01e02.Episode.Two.AlgernonWood-BlackBit\Fortitude.S01e02.Episode.Two.AlgernonWood-BlackBi.eng.srt","-a---"
"TestDrive:\Fortitude.S01e02.Episode.Two.AlgernonWood-BlackBit\Fortitude.S01e02.Episode.Two.AlgernonWood-BlackBit.avi","-a---"
"TestDrive:\Fortitude.S01e02.Episode.Two.AlgernonWood-BlackBit\Fortitude.S01e02.Episode.Two.AlgernonWood-BlackBit.ita.srt","-a---"
"TestDrive:\Fortitude.S01e02.Episode.Two.AlgernonWood-BlackBit\Fortitude.S01e02.Episode.Two.AlgernonWood-BlackBit.srt","-a---"
"TestDrive:\Fortitude S01E03 WEB-DL XviD-FUM[ettv]\Fortitude.S01E03.WEB-DL.XviD-FUM.avi","-a---"
"TestDrive:\Fortitude S01E03 WEB-DL XviD-FUM[ettv]\Torrent Downloaded From ExtraTorrent.cc.txt","-a---"
"TestDrive:\Fortitude S01E04 WEB-DL XviD-FUM[ettv]\Fortitude.S01E04.WEB-DL.XviD-FUM.avi","-a---"
"TestDrive:\Fortitude S01E04 WEB-DL XviD-FUM[ettv]\Torrent Downloaded From ExtraTorrent.cc.txt","-a---"
"TestDrive:\Fortitude S01E06 WEB-DL XviD-FUM[ettv]\Fortitude.S01E06.WEB-DL.XviD-FUM.avi","-a---"
"TestDrive:\Fortitude S01E06 WEB-DL XviD-FUM[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\Fortitude S01E07 WEB-DL XviD-FUM[ettv]\Fortitude.S01E07.WEB-DL.XviD-FUM.avi","-a---"
"TestDrive:\Fortitude S01E07 WEB-DL XviD-FUM[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\Fortitude S01E07 WEB-DL XviD-FUM[ettv]\Fortitude.S01E07.WEB-DL.XviD-FUM.srt","-a---"
"TestDrive:\Fortitude S01E08 WEB-DL XviD-FUM[ettv]\Fortitude.S01E08.WEB-DL.XviD-FUM.avi","-a---"
"TestDrive:\Fortitude S01E08 WEB-DL XviD-FUM[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\Fortitude S01E08 WEB-DL XviD-FUM[ettv]\Fortitude.S01E08.WEB-DL.XviD-FUM.srt","-a---"
"TestDrive:\Fortitude S01E09 WEB-DL XviD-FUM[ettv]\Fortitude.S01E09.WEB-DL.XviD-FUM.avi","-a---"
"TestDrive:\Fortitude S01E09 WEB-DL XviD-FUM[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\Fortitude S01E10 WEB-DL XviD-FUM[ettv]\Fortitude.S01E10.WEB-DL.XviD-FUM.avi","-a---"
"TestDrive:\Fortitude S01E10 WEB-DL XviD-FUM[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\The.Walking.Dead.S05E16.PROPER.HDTV.x264-KILLERS[ettv]\Sample","da---"
"TestDrive:\The.Walking.Dead.S05E16.PROPER.HDTV.x264-KILLERS[ettv]\The.Walking.Dead.S05E16.PROPER.HDTV.x264-KILLERS.mp4","-a---"
"TestDrive:\The.Walking.Dead.S05E16.PROPER.HDTV.x264-KILLERS[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\The.Walking.Dead.S05E16.PROPER.HDTV.x264-KILLERS[ettv]\the.walking.dead.s05e16.proper.hdtv.x264-killers.nfo","-a---"
"TestDrive:\The.Walking.Dead.S05E16.PROPER.HDTV.x264-KILLERS[ettv]\The.Walking.Dead.S05E16.PROPER.HDTV.x264-KILLERS.srt","-----"
"TestDrive:\The.Walking.Dead.S05E16.PROPER.HDTV.x264-KILLERS[ettv]\Sample\sample-the.walking.dead.s05e16.proper.hdtv.x264-killers.mp4","-a---"
"TestDrive:\Jordskott - S01E08 - 1280x720 - H.264 - SweSub.mp4\Jordskott - S01E08.mp4","-a---"
"TestDrive:\Jordskott - S01E08 - 1280x720 - H.264 - SweSub.mp4\Jordskott - S01E08.srt","-a---"
"TestDrive:\Game of Thrones S05E01 WEBRip XviD-FUM[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\Game of Thrones S05E02 WEBRip XviD-FUM[ettv]\Game.of.Thrones.S05E02.WEBRip.XviD-FUM.avi","-a---"
"TestDrive:\Game of Thrones S05E02 WEBRip XviD-FUM[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\Game of Thrones S05E02 WEBRip XviD-FUM[ettv]\Game.of.Thrones.S05E02.WEBRip.XviD-FUM.srt","-a---"
"TestDrive:\Game of Thrones S05E03 WEBRip XviD-FUM[ettv]\Game.of.Thrones.S05E03.WEBRip.XviD-FUM.avi","-a---"
"TestDrive:\Game of Thrones S05E03 WEBRip XviD-FUM[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\Game of Thrones S05E03 WEBRip XviD-FUM[ettv]\Game.of.Thrones.S05E03.WEBRip.XviD-FUM.srt","-a---"
"TestDrive:\Game of Thrones S05E04 WEBRip XviD-FUM[ettv]\Game.of.Thrones.S05E04.WEBRip.XviD-FUM.avi","-a---"
"TestDrive:\Game of Thrones S05E04 WEBRip XviD-FUM[ettv]\Torrent-Downloaded-From-extratorrent.cc.txt","-a---"
"TestDrive:\The Maze Runner (2014)\The.Maze.Runner.2014.720p.BluRay.x264.YIFY.mp4","-a---"
"TestDrive:\The Maze Runner (2014)\The.Maze.Runner.2014.720p.BluRay.x264.YIFY.srt","-a---"
"TestDrive:\Guitar.Hero.III.PC.The.Ultimate.Collection\GH3-TUC-Disc1-Essentials.iso","-a---"
"TestDrive:\Guitar.Hero.III.PC.The.Ultimate.Collection\GH3-TUC-Disc2-Customs.iso","-a---"
"TestDrive:\Guitar.Hero.III.PC.The.Ultimate.Collection\SongLists.txt","-a---"
"@ | ConvertFrom-Csv
    $files | %{
        $type = "File"
        if ($_.Mode -match "d") {
            $type = "Dir"
        }
        ni $_.FullName -ItemType $type | Out-Null
    }
}

Describe "Synology" {
    Context "Get-Movies" {

        Create-DownloadFolder
        $movies = Get-Movies -Path "Testdrive:\"

        It "finds some movies" {
            $movies.Length | Should Not Be 0
        }

        It "does not find folders with move extensions" {
            $foldersWithoutFiles = $movies | ?{ $_.Mode -match "d" }
            @($foldersWithoutFiles).Length | Should Be 0
        }
    }
}
